name: Bug report
description: Report a defect
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the problem?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: App/commit version
      placeholder: e.g. commit hash
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs or attach screenshots.
